### ISSUE TITLE
application/x-www-form-urlencoded content-type support

### ISSUE THREAD

**Issue by NazmiAltun** [jayrbolton/mock_microservice#3]
Hello,
This is quite simple and easy to use but need a bit detailed documentation. 
Container exposes port 5000 , which i believe,  should be added to the documentation. 
Anyway, I am trying to  mock  IdentityServer to generate bearer token. Bearer token request looks like this;

POST https://localhost:9090/connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 115
Host: localhost
grant_type=client_credentials&scope=api&client_id=private.client&client_secret=secret

and to mock it  I have added following  endpoint configurations

```
{
		"methods": ["POST" ],
		"path": "/connect/token",
		"response": {
			"status": "200",
			"body": {
					"access_token": "SECRET_ACCESS_TOKEN_HERE",
					"expires_in": 3600,
					"token_type": "Bearer"
			}
		}
}
```

However, this is not working. I guess it is because of the content-type of the request. Is there any way to make this work?

**Comment by jayrbolton** [comment]
We can add a content-type option for requests, with a default of application/json. If you know python, feel free to make a PR for it. Otherwise I can get to it this week.

**Comment by jayrbolton** [comment]
(I inserted a short text documenting the exposed port in the README btw. Feel free to make any PRs on the docs.)

**Comment by NazmiAltun** [comment]
Hello Jay,

Sadly I don't know phyton. It is alright. I will be watching the repo.
Thanks.

**Comment by jayrbolton** [comment]
Made some progress on this issue. Check out the second to last example here:
https://github.com/jayrbolton/mock_microservice/blob/master/test/endpoints.json
These changes are deployed to docker hub under the `mockservices/mock_json_service` image.
